// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// rp_pwm //
// ------ //

#define rp_pwm_wrap_target 0
#define rp_pwm_wrap 6
#define rp_pwm_pio_version 0

static const uint16_t rp_pwm_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 1
    0xb027, //  1: mov    x, osr          side 1
    0x1042, //  2: jmp    x--, 2          side 1
    0x80a0, //  3: pull   block           side 0
    0xa027, //  4: mov    x, osr          side 0
    0x0045, //  5: jmp    x--, 5          side 0
    0x0000, //  6: jmp    0               side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rp_pwm_program = {
    .instructions = rp_pwm_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = rp_pwm_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rp_pwm_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rp_pwm_wrap_target, offset + rp_pwm_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

